name: Android CI - debug apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable and build
        run: |
          chmod +x ./gradlew
          ./gradlew :composeApp:assembleDebug

      - name: Set APK path variables
        id: path_variables
        run: |
          echo "RELEASE_PATH_APK=composeApp/build/outputs/apk/debug/composeApp-debug.apk" >> $GITHUB_ENV
          echo "NAME_APK=MyApp.apk" >> $GITHUB_ENV

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.RELEASE_PATH_APK }}
          name: ${{ env.NAME_APK }}
          retention-days: 1

      - name: Upload reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: "**/build/compose/logs/*"
          retention-days: 1
